# -*- coding: utf-8 -*-
"""Untitled2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1abW8bvOwK3qiBNjTE7Vn-IYXv_63BM0O
"""

import pandas as pd
import matplotlib.pyplot as plt
import plotly.express as px
import plotly.graph_objects as go
from statsmodels.tsa.seasonal import seasonal_decompose
from statsmodels.graphics.tsaplots import plot_pacf
from statsmodels.tsa.arima_model import ARIMA
import statsmodels.api as sm
import matplotlib.pyplot as plt

data = pd.read_csv("/content/Thecleverprogrammer.csv")
print(data.head(20))

data["Date"] = pd.to_datetime(data["Date"],
                              format="%d/%m/%Y")
print(data.info())

plt. style.use('fivethirtyeight')
plt.figure(figsize=(10, 5))
plt.plot(data["Date"],data["Views"])
plt.title("Daily Traffic Forcasting data.com")
plt.show()

result = seasonal_decompose(data["Views"],
                            model='multiplicative',
                            period = 30)
fig = plt.figure()
fig = result.plot()
fig.set_size_inches(10, 5)

pd.plotting.autocorrelation_plot(data["Views"])

plot_pacf(data["Views"], lags =100)

p, d, q=5,1,2
model=sm.tsa.statespace.SARIMAX(data['Views'], order=(p,q,q),seasonal_order=(p, d, q, 12))
model=model.fit()
print(model.summary())

predictios =model.predict(len(data),len(data)+50)
print(predictios)

data["Views"].plot(legend=True,label="Training Data",figsize=(13,7))
predictios.plot(legend=True,label="predictions")